### ISSUE TITLE
centos7 yarn build issue.

### ISSUE THREAD

**Issue by leochan007** [taurusai/kungfu#44]
centos 7 x64  node 10.15.3 yarn 1.17.3

got this error:

[leo@192 kungfu]$ yarn build
yarn run v1.17.3
$ yarn wsrun --serial --fast-exit build
$ /home/leo/Documents/src_codes/kungfu/node_modules/.bin/wsrun --serial --fast-exit build
kungfu-core
$ yarn run build:cpp && yarn run build:pyi
$ cross-var pipenv run python python/build.py --build_type $npm_package_config_buildtype -l $npm_package_config_loglevel --arch $npm_package_config_arch --runtime $npm_package_config_runtime --node_version $npm_package_config_node --electron_version $npm_package_config_electron make
 | /home/leo/Documents/src_codes/kungfu/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
 |         throw e;
 |         ^
 | 
 | Error: Options {"loose":true} passed to /home/leo/Documents/src_codes/kungfu/node_modules/babel-preset-env/lib/index.js which does not accept options. (While processing preset: "/home/leo/Documents/src_codes/kungfu/node_modules/babel-preset-env/lib/index.js") (While processing preset: "/home/leo/Documents/src_codes/kungfu/node_modules/babel-preset-env/lib/index.js") (While processing preset: "/home/leo/Documents/src_codes/kungfu/node_modules/babel-preset-es2015/lib/index.js")
 |     at /home/leo/Documents/src_codes/kungfu/node_modules/babel-core/lib/transformation/file/options/option-manager.js:314:17
 |     at Array.map (<anonymous>)
 |     at OptionManager.resolvePresets (/home/leo/Documents/src_codes/kungfu/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
 |     at OptionManager.mergePresets (/home/leo/Documents/src_codes/kungfu/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
 |     at OptionManager.mergeOptions (/home/leo/Documents/src_codes/kungfu/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
 |     at OptionManager.init (/home/leo/Documents/src_codes/kungfu/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
 |     at compile (/home/leo/Documents/src_codes/kungfu/node_modules/babel-register/lib/node.js:103:45)
 |     at loader (/home/leo/Documents/src_codes/kungfu/node_modules/babel-register/lib/node.js:144:14)
 |     at Object.require.extensions.(anonymous function) [as .js] (/home/leo/Documents/src_codes/kungfu/node_modules/babel-register/lib/node.js:154:7)
 |     at Module.load (internal/modules/cjs/loader.js:600:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 | `yarn build` failed with exit code 1
Stopping 1 active children
Aborted execution due to previous error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by leochan007** [comment]
remove "_" in parent directory is OK. @taurusai plz update README.md to let others know this issue.
